FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    wget \
    openjdk-8-jdk \
    python3.10 \
    python3-pip \
    xvfb \
    scrot \
    xdotool \
    tigervnc-viewer \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install robotframework

ENV DISPLAY=:99

WORKDIR /test

COPY /test/auto .
