FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    wget \
    openjdk-8-jdk \
    python3.10 \
    python3-pip \
    xvfb \
    tigervnc-viewer \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install robotframework robotframework-sikulixlibrary

RUN mkdir -p /opt/sikulix
WORKDIR /opt/sikulix
RUN wget https://launchpad.net/sikuli/sikulix/2.0.5/+download/sikulixide-2.0.5-lux.jar -O sikulix.jar

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
ENV SIKULI_HOME=/opt/sikulix
ENV DISPLAY=:99

WORKDIR /test

COPY /test/auto .
