FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV QT_QPA_PLATFORM=xcb
ENV DISPLAY=:1

###########################################
# Install dependencies for Qt Application #
###########################################

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libgl1-mesa-dev \
    libglib2.0-dev \
    qt6-base-dev \
    qt6-declarative-dev \
    qt6-tools-dev-tools \
    qt6-tools-dev \
    qml6-module-qtquick-controls \
    qml6-module-qtquick-layouts \
    qml6-module-qtquick \
    qml6-module-qtqml-workerscript \
    qml6-module-qtquick-templates \
    qml6-module-qtquick-window \
    libqt6sql6-psql \
    cmake \
    xvfb \
    x11vnc \
    python3.10 \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install google-auth google-auth-oauthlib google-api-python-client

WORKDIR /app

COPY /app .

RUN qtchooser -install qt6 $(which qmake6)

RUN mkdir build

WORKDIR /app/build

RUN qmake6 ../CFSW.pro && make

RUN mkdir Tools token

WORKDIR /app/build/Tools

COPY /Tools .

WORKDIR /app/build

# VNC port
EXPOSE 5900
